version: '2'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"

    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        links:
            - rabbit
        depends_on:
            - rabbit
    database:
        hostname: mongo
        host: 0.0.0.0
        image: mongo:latest
        ports:
            - "27017:27017"
networks:
    code_net:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1